import Header from "@/app/_components/Header/Header";
import "./globals.scss";
import AuthSessionProvider from "@/app/_providers/SessionProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body
      // className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <AuthSessionProvider>
          <div className="wrapper">
            <div className="container">{children}</div>
          </div>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
