import Header from "@/app/_components/Header/Header";
import "@/app/globals.scss";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MapLayout({ children }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
